version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW 
    restart: always
    volumes:
      - {MARIADB_DATA}:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    build: .
    restart: always
    volumes:
      - {NEXTCLOUD_DATA}:/var/www/html/
    environment:
      - MARIADB_HOST=db
      - REDIS_HOST=redis
    ports:
      - 9005:9000
    env_file:
      - nextcloud.env
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /srv/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
