version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW 
    restart: always
    volumes:
      - /srv/docker/nextcloud_db/:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./nextcloud_app
    restart: always
    volumes:
      - /srv/nextcloud/:/var/www/html/
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=5000M
    ports:
      - 9005:9000
    env_file:
      - nextcloud.env
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /srv/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
